run-dev:
	APP_PORT="changeme" \
	JWT_KEY="changeme" \
	JWT_EXPIRY="changeme" \
	CLIENT_HOST="changeme" \
	CLIENT_PORT="changeme" \
	CLIENT_TIMEOUT="changeme" \
	CONVERTER_HOST="changeme" \
	CONVERTER_PORT="changeme" \
	CONVERTER_API="changeme" \
	CONVERTER_TIMEOUT="changeme" \
	go run cmd/main.go