run-dev:
	APP_PORT="changeme" \
	POSTGRES_HOST="changeme" \
	POSTGRES_PORT="changeme" \
	POSTGRES_USER="changeme" \
	POSTGRES_PASS="changeme" \
	POSTGRES_DB_NAME="changeme" \
	POSTGRES_SSLMODE="changeme" \
	POSTGRES_CONNECTION_MAX_LIFETIME="changeme" \
	POSTGRES_MAX_OPEN_CONNECTION="changeme" \
	POSTGRES_MAX_IDLE_CONNECTION="changeme" \
	JWT_KEY="changeme" \
	JWT_EXPIRY="changeme" \
	go run cmd/main.go